[tool.poetry]
name = "udemy-learning"
version = "0.1.0"
description = "This is the a learning environment"
authors = ["Marco"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
